### ISSUE TITLE
Rounding issues in UI

### ISSUE THREAD

**Issue by Hekku2** [mande-labs/mande-chain#45]
Values on staking view are rounded to decimals, which causes issues where user is unable to unstake their tokens.

What happened: 

1. User has staked 1.9993 $MAND  -> UI shows 2.0 $MAND
2. User tries to unstake 2.0 $MAND because that's what the UI shows
3. Unstake button on loads briefly without giving any error message in UI (actual response was "execution reverted: TrustDrops::Insufficient staked amount")

What should have happened
1. UI shows 1.9993 $MAND for user (or rounded to max precision needed)
2. If user tries still unstake wrong amount, there is an error shown, or the button is disabled, or something similar that the user knows what happens.

Picture of the view, just to clarify the view I'm talking about:
![image](https://github.com/mande-labs/mande-chain/assets/2670916/267b9747-ae7d-4484-9422-925723e4fc85)

My guess of problem:
https://github.com/mande-labs/trust-drops/blob/50e68c18af5cec4c569f1c66ac0b0bd6d19cabff/trust-drops-ui/src/pages/Dashboard.jsx#L248

**Comment by prtk418** [comment]
Hey @Hekku2 nice catch. why dont you create a PR with fix :)

**Comment by Hekku2** [comment]
Okay, what is the correct precision for this token?

**Comment by prtk418** [comment]
Basically we want to use this function to apply truncation, instead of rounding off - https://github.com/mande-labs/trust-drops/blob/queue/trust-drops-ui/src/pages/Dashboard.jsx#L135

This function truncates till 4 decimals, we need 2 decimals for this case

**Comment by Hekku2** [comment]
I don't think that fixes the issue, let me clarify I understood this correctly:

For example value "0x0000000000000000000000000000000000000000000000001bc167097e449000" (1.999993), if I use `truncateAmount("0x0000000000000000000000000000000000000000000000001bc167097e449000")`, it returns 2.0000, which hides the actual staked value from user (using 2 decimals would make the situation just as bad as before). If add more precision (let's say 10 decimals), it returns "1.9999930000". This would let unstake the correct amount. To be fair, it's uglier, but it doesn't prevent user using this.

**Comment by prtk418** [comment]
ex: if `data.amount= 14996000000000000000` when you use `truncateAmount(data.amount)` it would return `14.9960` right now

**Comment by prtk418** [comment]
> I don't think that fixes the issue, let me clarify I understood this correctly:
> 
> For example value "0x0000000000000000000000000000000000000000000000001bc167097e449000" (1.999993), if I use `truncateAmount("0x0000000000000000000000000000000000000000000000001bc167097e449000")`, it returns 2.0000, which hides the actual staked value from user (using 2 decimals would make the situation just as bad as before). If add more precision (let's say 10 decimals), it returns "1.9999930000". This would let unstake the correct amount. To be fair, it's uglier, but it doesn't prevent user using this.

I get your point, what if we update logic of `truncateAmount` to something like this - 
```
  const truncateAmount = (amount, precision=4) => {
    const amtStr = amount.toString();
    const finalStr = amtStr.substring(0, amtStr.length - (18 - precision));
    return ethers.utils.formatUnits(finalStr, precision);
  };
```

and then use it like this - `truncateAmount(data.amount, 2)` for displaying staked / stake received amount

**Comment by Hekku2** [comment]
I think that will cause problems because the same method also handled hexadecimals.

How about (not my best work, It's been a long time since I wrote typescript/javascript):

```javascript
  const truncateAmount = (amount, precision=4) => {
    const formattedAmount = ethers.utils.formatUnits(amount);
    let [whole, decimal] = formattedAmount.split('.');
    // toFixed will add imprecision to the number in some cases (parseFloat("1.9999").toFixed(18)),
    // so we manually pad the number
    while (decimal && decimal.length < precision) {
      decimal += '0';
    }
    return `${whole}.${decimal}`;
  };
```

It should add the trailing zeroes, but also doesn't lose the precision returned from the API. That we user is provided a clean value, but also the details are shown if user has used some 0.00001 values for some reason.

I can create PR later today.

**Comment by Hekku2** [comment]
I tried to link this issue directly by it didn't allow, so here is the PR https://github.com/mande-labs/trust-drops/pull/5
